PART1

In [1]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('/Users/houhiroshisakai/Desktop/Schulich/Term 2/MBAN 5110/dataset_lm.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422 entries, 0 to 421
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Dependent Var        422 non-null    float64
 1   Explanatory Var #1   422 non-null    float64
 2   Explanatory Var #2   422 non-null    float64
 3   Explanatory Var #3   422 non-null    int64  
 4   Explanatory Var #4   422 non-null    float64
 5   Explanatory Var #5   422 non-null    float64
 6   Explanatory Var #6   422 non-null    float64
 7   Explanatory Var #7   422 non-null    float64
 8   Explanatory Var #8   422 non-null    int64  
 9   Explanatory Var #9   422 non-null    float64
 10  Explanatory Var #10  422 non-null    float64
 11  Explanatory Var #11  422 non-null    float64
 12  Explanatory Var #12  422 non-null    float64
 13  Explanatory Var #13  422 non-null    int64  
 14  Explanatory Var #14  422 non-null    float64
 15  Explanatory Var #15  422 non-null    flo

In [4]:
y = df['Dependent Var']
x = df.drop('Dependent Var', axis = 1)
x = sm.add_constant(x)

In [26]:
model = sm.OLS(y,x).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:          Dependent Var   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 7.593e+30
Date:                Wed, 25 Oct 2023   Prob (F-statistic):               0.00
Time:                        10:11:44   Log-Likelihood:                 12339.
No. Observations:                 422   AIC:                        -2.465e+04
Df Residuals:                     406   BIC:                        -2.458e+04
Df Model:                          15                                         
Covariance Type:            nonrobust                                         
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  32.0000   4

PART2

In [6]:
r = model.resid
std = np.std(r)
for i in range(1,4):
    autocorrelations = r.autocorr(lag=i)
    print(autocorrelations)

0.058414467865043104
0.08644975281695741
-0.012221602816729942


In [7]:
gls_model = sm.GLS(y, x).fit()
print(gls_model.summary())

                            GLS Regression Results                            
Dep. Variable:          Dependent Var   R-squared:                       1.000
Model:                            GLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 7.593e+30
Date:                Tue, 24 Oct 2023   Prob (F-statistic):               0.00
Time:                        15:24:46   Log-Likelihood:                 12339.
No. Observations:                 422   AIC:                        -2.465e+04
Df Residuals:                     406   BIC:                        -2.458e+04
Df Model:                          15                                         
Covariance Type:            nonrobust                                         
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  32.0000   4

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.5, random_state=0)

In [9]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha = 1)
lasso.fit(x_train, y_train)

Lasso(alpha=1)

In [10]:
from sklearn.metrics import mean_absolute_percentage_error

prediction = lasso.predict(x_test)
mae = mean_absolute_percentage_error(y_test, prediction)
mae = mae * 100
print(mae)

3.947673796221206


In [11]:
from sklearn.model_selection import GridSearchCV
parameters = {'alpha': np.linspace(0.1, 10, 100)}
lasso = Lasso()
grid = GridSearchCV(lasso, parameters, scoring='neg_mean_absolute_error')
grid.fit(x,y)

#Optimal alpha
print(f'Optimal alpha: {grid.best_params_}')

Optimal alpha: {'alpha': 0.1}


PART D

In [13]:
data = {
    'Month' : list(range(1,26)),
    'Demand' : [100,112,107,102,91,85,84,85,79,81,134,86,99,89,
                111,114,118, 163, 193,143,144,202,158,160,144],
    'Advanced_Demand' : [71,30,75,64,41,51,42,51,57,49,134,
                         52,99,56,81,79,73,163,193,99,91,202,105,101,96]
}

df1 = pd.DataFrame(data)

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Month            25 non-null     int64
 1   Demand           25 non-null     int64
 2   Advanced_Demand  25 non-null     int64
dtypes: int64(3)
memory usage: 728.0 bytes


In [16]:
df1

Month  Demand  Advanced_Demand
0       1     100               71
1       2     112               30
2       3     107               75
3       4     102               64
4       5      91               41
5       6      85               51
6       7      84               42
7       8      85               51
8       9      79               57
9      10      81               49
10     11     134              134
11     12      86               52
12     13      99               99
13     14      89               56
14     15     111               81
15     16     114               79
16     17     118               73
17     18     163              163
18     19     193              193
19     20     143               99
20     21     144               91
21     22     202              202
22     23     158              105
23     24     160              101
24     25     144               96

In [22]:
from sklearn.linear_model import LinearRegression
y1 = df1['Demand'][1:]
x1 = df1['Demand'][:-1].values.reshape(-1,1) #1D to 2D 
l = np.array(df1['Advanced_Demand'][1:])

#Building Regression Model
ols_model = LinearRegression()
ols_model.fit(x1,y1)
#Grabing beta value
ols_beta = ols_model.coef_
print(ols_beta)

[0.71377905]


In [23]:
ols_predictions = ols_model.predict(x1)
ols_predictions

array([107.08071744, 115.64606602, 112.07717078, 108.50827554,
       100.656706  ,  96.37403171,  95.66025266,  96.37403171,
        92.09135741,  93.51891551, 131.3492051 ,  97.08781075,
       106.36693839,  99.2291479 , 114.93228698, 117.07362412,
       119.92874032, 152.04879751, 173.46216898, 137.77321654,
       138.48699559, 179.88618042, 148.47990227, 149.90746037])

In [30]:
#Evaluating ols model
from sklearn.metrics import mean_squared_error
mse_ols = mean_squared_error(y1, ols_predictions)
print('MSE for OLS is ', mse_ols)

MSE for OLS is  615.1663500007506


In [35]:
#Ridge Model
from sklearn.linear_model import Ridge
from sklearn.linear_model import RidgeCV

#Define lambdas value
alphas = np.logspace(-10,10,21)

#Looking for the best value of lambda by Cross validation
ridge_cv = RidgeCV(alphas = alphas, store_cv_values=True)
ridge_cv.fit(x1,y1)

best_lambda = ridge_cv.alpha_
best_lambda


1000.0

In [36]:
ridge_model = Ridge(alpha = best_lambda)
ridge_model.fit(x1, y1)

ridge_beta = ridge_model.coef_
ridge_beta

array([0.690457])

In [37]:
ridge_predictions = ridge_model.predict(x1)
ridge_predictions

array([107.50828832, 115.79377233, 112.34148732, 108.88920232,
       101.29417531,  97.1514333 ,  96.4609763 ,  97.1514333 ,
        93.0086913 ,  94.3896053 , 130.98382635,  97.8418903 ,
       106.81783131,  99.91326131, 115.10331533, 117.17468633,
       119.93651433, 151.00707938, 171.7207894 , 137.19793936,
       137.88839636, 177.93490241, 147.55479437, 148.93570837])

In [38]:
#Evaluating Ridge model
mse_ridge = mean_squared_error(y1, ridge_predictions)
print('MSE for Ridge is ', mse_ols)

MSE for Ridge is  615.1663500007506


In [40]:
#Lasso Model
from sklearn.linear_model import LassoCV

#Define lambdas value
alphas = np.logspace(-10,10,21)

#Looking for the best value of lambda by Cross validation
lasso_cv = LassoCV(alphas = alphas)
lasso_cv.fit(x1,y1)

best_lambda_lasso = lasso_cv.alpha_
best_lambda_lasso

1e-10

In [41]:
lasso_model = Lasso(alpha = best_lambda_lasso)
lasso_model.fit(x1, y1)

#Grathering beta value
lasso_beta = lasso_model.coef_
lasso_beta

array([0.71377905])

In [42]:
lasso_predictions = lasso_model.predict(x1)
lasso_predictions

array([107.08071744, 115.64606602, 112.07717078, 108.50827554,
       100.656706  ,  96.37403171,  95.66025266,  96.37403171,
        92.09135741,  93.51891551, 131.3492051 ,  97.08781075,
       106.36693839,  99.2291479 , 114.93228698, 117.07362412,
       119.92874032, 152.04879751, 173.46216898, 137.77321654,
       138.48699559, 179.88618042, 148.47990227, 149.90746037])

In [43]:
#Evaluating Lasso Model
mse_lasso = mean_squared_error(y1, lasso_predictions)
print('MSE for Lasso is ', mse_lasso)

MSE for Lasso is  615.1663500007506
